name: VPN_Guncelle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Bu satÄ±r bota 'yazabilirsin' emri verir
    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gereksinimleri Kur
        run: pip install requests

      - name: Botu Calistir
        run: python Bot.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add abone.txt
          git commit -m "VPN Listesi Guncellendi" || echo "Degisiklik yok"
          git push origin ana --force
